/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Mon Jun  3 13:14:22 KST 2013
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_MAGNUS_H
#define BOARD_REV_MAGNUS_H

/*
Current MODEL ID is T_MAGNUS 
LINUX Kernel Define & macro function is as follows
#define CONFIG_MACH_MSM8960_MAGNUS
machine_is_msm8960_magnus() function
*/

#define PT10  0x01
#define PT20  0x02
#define WS10  0x03
#define WS11  0x04
#define WS20  0x05
#define TP10  0x06
#define TP20  0x07
#define TP30  0x08

#define BOARD_VER			TP20
#define T_MAGNUS
#define FIRM_VER			"KAUSS15"
#define SYS_MODEL_NAME			"MAGNUS"
#define PANTECH_MODEL_NAME		"PantechP9090"
#define SYS_PROJECT_NAME		"MAGNUS"
#define FS_USER_DATA_VER		"7"
#define PANTECH_STORAGE_INTERNAL_EMUL
#define FEATURE_AARM_RELEASE_MODE

#endif /*BOARD_REV_MAGNUS_H*/
